name: Documentation Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'v*-branch'
  push:
    branches:
      - main
      - 'v*-branch'
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: nrfconnect/action-checkout-west-update@main
        with:
          path: nrf70_bm_ws/nrf70-bm

      - name: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-doc-pip

      - name: Install packages
        working-directory: nrf70_bm_ws
        run: |
          sudo apt update
          sudo apt-get install -y ninja-build mscgen plantuml
          sudo snap install yq
          DOXYGEN_VERSION=$(yq ".doxygen.version" ./nrf/scripts/tools-versions-linux.yml)
          wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
          tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          echo "${PWD}/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        working-directory: nrf70_bm_ws
        run: |
          sudo pip3 install -U setuptools wheel pip
          pip3 install -r nrf/doc/requirements.txt

      - name: West zephyr-export
        working-directory: nrf70_bm_ws
        run: |
          west zephyr-export

      - name: Build documentation
        working-directory: nrf70_bm_ws/nrf70-bm
        run: ./build-docs.sh

      - name: Prepare legacy upload
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'external') || contains(github.event.pull_request.labels.*.name, 'CI-trusted-author') }}
        working-directory: nrf70_bm_ws/nrf70-bm/nrf70_bm_lib
        run: |
          MONITOR="monitor_${{ github.run_id }}.txt"

          # Create documentation upload files
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ARCHIVE="nrf70-bm-docs-${{ github.event.number }}.zip"
            echo "publish2 dev PR-${{ github.event.number }} ${ARCHIVE}" > "${MONITOR}"
            echo "${{ github.event.number }}" > pr.txt
          else
            if [ -z "${VERSION}" ]; then
              echo "Not a release or latest, skipping publish"
              exit 0
            fi

            ARCHIVE="nrf70-bm-docs-${VERSION}.zip"
            echo "publish2 main ${VERSION} ${ARCHIVE}" > "${MONITOR}"
          fi

          cd docs/build/html
          zip -rq "${ARCHIVE}" .
          mv "${ARCHIVE}" ../../../

      - name: Store
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'external') || contains(github.event.pull_request.labels.*.name, 'CI-trusted-author') }}
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            nrf70_bm_ws/nrf70-bm/nrf70_bm_lib/*.zip
            nrf70_bm_ws/nrf70-bm/nrf70_bm_lib/monitor*.txt
            nrf70_bm_ws/nrf70-bm/nrf70_bm_lib/pr.txt
